functional:
  - Пользователь имеет возможность зарегистрироваться
  - Пользователь имеет возможность выбрать сложность игры
  - Пользователь имеет возможность выбрать тип соперника
  - Пользователь имеет возможность выбрать язык программирования
  - Пользователь имеет возможность присоединиться к запущенной игре в качестве зрителя
  - Пользователь имеет возможность оставлять сообщения в чатах
  - Пользователь имеет возможность просматривать запись игры
  - Сайт рассчитывает рейтинг пользователя в сумме результатов пройденных игр
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Отображение статуса "Онлайн"/"Оффлайн" у пользователей
  - История активности пользователя должна сохранятся и отображаться в его профиле
  - При создании игры доступен поиск среди зарегистрированных игроков
  - Пользователь имеет возможность видеть статусы других игр ("Ожидает соперника", "В процессе")
  
